-- Insert sample projects
INSERT INTO projects (name, description, github_url, demo_url, technologies, primary_language, stars_count, featured, image_url) VALUES
('Pathtracer', 
 'A high-performance ray tracing renderer written in Rust, implementing physically-based rendering techniques for realistic lighting and materials.', 
 'https://github.com/eliasstepanik/pathtracer', 
 NULL, 
 ARRAY['Rust', 'Ray Tracing', 'Computer Graphics', 'Parallel Computing', 'SIMD'], 
 'Rust', 
 127, 
 true, 
 '/public/images/pathtracer-preview.jpg'),

('Bevy-TileSystem', 
 'A flexible and performant tile-based game engine system for the Bevy game engine, supporting infinite worlds and chunk-based loading.', 
 'https://github.com/eliasstepanik/Bevy-TileSystem', 
 NULL, 
 ARRAY['Rust', 'Bevy', 'Game Engine', 'ECS', 'Procedural Generation'], 
 'Rust', 
 89, 
 false, 
 '/public/images/bevy-tilesystem-preview.jpg'),

('voxel-simulation', 
 'GPU-accelerated voxel world simulation with fluid dynamics and particle systems, featuring real-time water flow and physics interactions.', 
 'https://github.com/eliasstepanik/voxel-simulation', 
 'https://voxel-demo.example.com', 
 ARRAY['Rust', 'WebGPU', 'WGSL', 'Simulation', 'Physics'], 
 'Rust', 
 156, 
 false, 
 '/public/images/voxel-simulation-preview.jpg'),

('FluidSimulation', 
 'Real-time fluid dynamics simulation using SPH (Smoothed-particle hydrodynamics) implemented in C#, capable of simulating thousands of particles.', 
 'https://github.com/eliasstepanik/FluidSimulation', 
 NULL, 
 ARRAY['C#', 'Unity', 'Physics', 'Simulation', 'HLSL', 'Compute Shaders'], 
 'C#', 
 203, 
 true, 
 '/public/images/fluid-simulation-preview.jpg');
